### ISSUE TITLE
Map doesn't seem to update with changes to wvw status

### ISSUE THREAD

**Issue by cgibbsgithub** [agaertner/bhm-mistwar#22]
Not sure if there is an incompatibility issue, but my Mistwar doesn't refresh with changes to team territory etc.
It shows "refreshing" but the data doesn't update.

**Comment by agaertner** [comment]
This is a known issue among every WvW addon.

```
The match API which third-party applications - like Mistwar - are using to get info about your WvW match is only updated when one of the following occurs:
    • The match ticks or ends, or
    • An objective flips, or
    • A guild claims an objective.
A tier change happening does not trigger a refresh of the API. A tier will appear frozen until one of the triggers updates the API.
```
Ref.: <https://github.com/arenanet/api-cdi/issues/417> (technicalities)

When WvW population is high the API gets throttled.

**Comment by cgibbsgithub** [comment]
Interesting - I've tried a few times but haven't been able to see the minimap reflect the "real" map. I wonder if my client is pulling a different matchup. Is the addon supporting the new world assignment system using wvw guild? (which isn't the guild I am representing, if that matters)

Example world status mismatch:
![1](https://github.com/user-attachments/assets/75fa998f-0c83-4e67-b67c-efe2b0faf46e)
![2](https://github.com/user-attachments/assets/3533da26-9378-45c5-abcc-ecce0f0410eb)

**Comment by cgibbsgithub** [comment]
I have been digging in my API and I think I see the issue.

From /account I have a value of world=2008, which is in /wvw/matches/overview/2-3
In match 2-3, the all_worlds.blue values are 12008, 2204, 2008

If I look at my /accounts/wvw I have a team=12007
Looking at /wvw/matches/overview/2-1 I see all_worlds.blue values of 12007, 2203, 2007.

So, if I interpret correctly, the wvw minimap is displaying the live data for match 2-3, but I'm actually playing in match 2-1.

**Comment by cgibbsgithub** [comment]
Sounds like the last version update is to address this, haven't tested but assuming it works this is closed :)
Thank you!
